import { Injectable } from "@nestjs/common";
import {
  IValidationStrategy,
  ValidationReport,
  RawQuestion,
} from "../interfaces/validation-strategy.interface";
import {
  GenerationContext,
  HybridPayload,
} from "../interfaces/generation-context.interface";

/**
 * HybridValidator
 *
 * Validates questions generated by the HYBRID strategy.
 * Checks: graph integrity, logical correctness, scenario completeness.
 */
@Injectable()
export class HybridValidator implements IValidationStrategy {
  async validate(
    context: GenerationContext,
    question: RawQuestion,
  ): Promise<ValidationReport> {
    const errors: string[] = [];
    const warnings: string[] = [];
    const payload = context.payload as HybridPayload;

    // 1. Question text must not be empty
    if (!question.questionText?.trim()) {
      errors.push("Question text is empty.");
    }

    // 2. Must have exactly 4 options
    if (!question.options || question.options.length !== 4) {
      errors.push(`Expected 4 options, got ${question.options?.length ?? 0}.`);
    }

    // 3. Correct answer must be one of A/B/C/D
    const validAnswers = ["A", "B", "C", "D"];
    if (!validAnswers.includes(question.correctAnswer?.toUpperCase())) {
      errors.push(
        `Correct answer "${question.correctAnswer}" is not a valid option (A/B/C/D).`,
      );
    }

    // 4. Validate graph is present and non-empty
    const graph = payload.relationshipGraph;
    if (!graph || Object.keys(graph).length === 0) {
      errors.push(
        "Relationship graph is empty — cannot generate hybrid question.",
      );
    }

    // 5. Validate entities exist in the graph
    const entities = (graph?.entities as string[]) ?? [];
    if (entities.length === 0) {
      errors.push("No entities found in the relationship graph.");
    }

    // 6. Validate edges exist
    const edges = (graph?.edges as unknown[]) ?? [];
    if (edges.length === 0) {
      warnings.push(
        "No relationship edges in graph. The scenario may be trivial.",
      );
    }

    // 7. Graph acyclicity check (basic: no entity appears in circular chain)
    const hasCycle = this.detectCycle(entities, edges as any);
    if (hasCycle) {
      warnings.push(
        "Relationship graph may contain cycles. Verify logical correctness.",
      );
    }

    // 8. Explanation must include step-by-step reasoning
    if (!question.explanation?.trim()) {
      warnings.push(
        "Explanation is empty — logical reasoning questions require step-by-step explanation.",
      );
    }

    return { valid: errors.length === 0, errors, warnings };
  }

  private detectCycle(
    entities: string[],
    edges: Array<{ from: string; to: string }>,
  ): boolean {
    const adjacency = new Map<string, string[]>();
    for (const entity of entities) {
      adjacency.set(entity, []);
    }
    for (const edge of edges) {
      adjacency.get(edge.from)?.push(edge.to);
    }

    const visited = new Set<string>();
    const inStack = new Set<string>();

    const dfs = (node: string): boolean => {
      visited.add(node);
      inStack.add(node);
      for (const neighbor of adjacency.get(node) ?? []) {
        if (!visited.has(neighbor) && dfs(neighbor)) return true;
        if (inStack.has(neighbor)) return true;
      }
      inStack.delete(node);
      return false;
    };

    for (const entity of entities) {
      if (!visited.has(entity) && dfs(entity)) return true;
    }
    return false;
  }
}
