import { Injectable } from "@nestjs/common";
import {
  IValidationStrategy,
  ValidationReport,
  RawQuestion,
} from "../interfaces/validation-strategy.interface";
import {
  GenerationContext,
  VariableData,
} from "../interfaces/generation-context.interface";

/**
 * VariableValidator
 *
 * Validates questions generated by the VARIABLE strategy.
 * Checks: formula correctness, answer present in options, constraint compliance.
 */
@Injectable()
export class VariableValidator implements IValidationStrategy {
  async validate(
    context: GenerationContext,
    question: RawQuestion,
  ): Promise<ValidationReport> {
    const errors: string[] = [];
    const warnings: string[] = [];
    const payload = context.payload as VariableData;

    // 1. Question text must not be empty
    if (!question.questionText?.trim()) {
      errors.push("Question text is empty.");
    }

    // 2. Must have exactly 4 options
    if (!question.options || question.options.length !== 4) {
      errors.push(`Expected 4 options, got ${question.options?.length ?? 0}.`);
    }

    // 3. Correct answer must be one of A/B/C/D
    const validAnswers = ["A", "B", "C", "D"];
    if (!validAnswers.includes(question.correctAnswer?.toUpperCase())) {
      errors.push(
        `Correct answer "${question.correctAnswer}" is not a valid option (A/B/C/D).`,
      );
    }

    // 4. Explanation must not be empty
    if (!question.explanation?.trim()) {
      warnings.push("Explanation is empty — consider adding one.");
    }

    // 5. Variables must have been resolved (non-empty)
    if (!payload.variables || Object.keys(payload.variables).length === 0) {
      errors.push(
        "No variables were resolved for this VARIABLE strategy question.",
      );
    }

    // 6. Warn if the hydrated question still contains unresolved placeholders
    if (payload.hydratedQuestion?.includes("{{")) {
      warnings.push(
        "Hydrated question still contains unresolved placeholders ({{...}}).",
      );
    }

    return { valid: errors.length === 0, errors, warnings };
  }
}
