import {
  PromptBuilderService,
  PromptBuilderInput,
} from "../prompts/prompt-builder.service";
import { ResponseValidatorService } from "../validators/response-validator.service";
import { GeneratedQuestionDto } from "../dto/generated-question.dto";

describe("SGE Strategy Integration", () => {
  let promptBuilder: PromptBuilderService;
  let responseValidator: ResponseValidatorService;

  beforeEach(() => {
    promptBuilder = new PromptBuilderService();
    responseValidator = new ResponseValidatorService();
  });

  describe("VARIABLE Strategy", () => {
    it("should build prompt and pass validation with calculated answer match", () => {
      const input: PromptBuilderInput = {
        template: {
          id: "tpl_math",
          name: "Math Template",
          conceptKey: "percentages",
          difficultyLevel: "EASY",
          questionType: "mcq",
          structure: {
            questionTemplate:
              "If the old price is {oldPrice} and it increases, the new price is {newPrice}.",
          },
          variableSchema: {},
          constraints: {},
          solutionSchema: { steps: ["Verify price change"] },
          generationStrategy: "VARIABLE",
        },
        variableValues: { oldPrice: 100, newPrice: 120, correctAnswer: "20" },
      };

      const prompt = promptBuilder.buildPrompt(input);
      expect(prompt).toContain("Generation Strategy: VARIABLE");
      expect(prompt).toContain("oldPrice = 100");
      expect(prompt).toContain("newPrice = 120");
      expect(prompt).toContain("Correct Answer Value = 20");

      const question: GeneratedQuestionDto = {
        question:
          "If the old price is 100 and it increases, the new price is 120.",
        options: ["10", "15", "20", "25"],
        correctAnswer: "20",
        answer: "20",
        explanation:
          "Concept\nPercentages\n\nFormula / Reasoning\nNone\n\nStep-by-Step Solution\n120 - 100 = 20\n\nFinal Answer\n20",
        difficulty: "easy",
        topic: "percentages",
        metadata: {
          generationStrategy: "VARIABLE",
          variables: { oldPrice: 100, newPrice: 120, correctAnswer: "20" },
        },
      };

      expect(() =>
        responseValidator.validate(
          question,
          "easy",
          "percentages",
          input.template,
        ),
      ).not.toThrow();
    });

    it("should fail validation when the explanation does not reference the correct answer", () => {
      const template = {
        id: "tpl_math",
        name: "Math Template",
        conceptKey: "percentages",
        difficultyLevel: "EASY",
        questionType: "mcq",
        structure: {},
        variableSchema: {},
        constraints: {},
        generationStrategy: "VARIABLE",
      };

      const question: GeneratedQuestionDto = {
        question: "If the old price is 100 and it increases, the new price is 120.",
        options: ["10", "15", "20", "25"],
        correctAnswer: "20",
        answer: "20",
        explanation: "Concept\n\nFormula / Reasoning\n\nStep-by-Step Solution\n\nFinal Answer\nThis is a different answer.",
        difficulty: "easy",
        topic: "percentages",
        metadata: {
          generationStrategy: "VARIABLE",
          variables: { oldPrice: 100, newPrice: 120, correctAnswer: "20" },
        },
      };

      expect(() =>
        responseValidator.validate(question, "easy", "percentages", template),
      ).toThrow("Explanation alignment check failed");
    });

    it("should fail validation if LLM correct answer deviates from calculated answer", () => {
      const template = {
        id: "tpl_math",
        name: "Math Template",
        conceptKey: "percentages",
        difficultyLevel: "EASY",
        questionType: "mcq",
        structure: {},
        variableSchema: {},
        constraints: {},
        generationStrategy: "VARIABLE",
      };

      const question: GeneratedQuestionDto = {
        question:
          "If the old price is 100 and it increases, the new price is 120. (long question)",
        options: ["10", "15", "20", "30"],
        correctAnswer: "30", // Bad answer generated by LLM
        answer: "30",
        explanation:
          "Concept\n\nFormula / Reasoning\n\nStep-by-Step Solution\n\nFinal Answer\n30",
        difficulty: "easy",
        topic: "percentages",
        metadata: {
          generationStrategy: "VARIABLE",
          variables: { oldPrice: 100, newPrice: 120, correctAnswer: "20" }, // Computed was 20
        },
      };

      expect(() =>
        responseValidator.validate(question, "easy", "percentages", template),
      ).toThrow("Math validation failed");
    });
  });

  describe("DATASET Strategy", () => {
    it("should build prompt and validate structured vocabulary questions", () => {
      const input: PromptBuilderInput = {
        template: {
          id: "tpl_vocab",
          name: "Vocabulary Synonym",
          conceptKey: "synonyms",
          difficultyLevel: "MEDIUM",
          questionType: "mcq",
          structure: {},
          variableSchema: {},
          constraints: {},
          generationStrategy: "DATASET",
        },
        variableValues: {},
        datasetItem: {
          content:
            "Abundant means present in great quantity; more than adequate; oversufficient.",
          metadata: { word: "abundant", synonym: "plentiful" },
        },
      };

      const prompt = promptBuilder.buildPrompt(input);
      expect(prompt).toContain("Generation Strategy: DATASET");
      expect(prompt).toContain("Abundant means present in great quantity");

      const question: GeneratedQuestionDto = {
        question: "Select the synonym of the word 'Abundant' (Long text stem)",
        options: ["Plentiful", "Scarce", "Few", "Tiny"],
        correctAnswer: "Plentiful",
        answer: "Plentiful",
        explanation:
          "Concept\nVocabulary\n\nFormula / Reasoning\nNone\n\nStep-by-Step Solution\nPlentiful is synonym.\n\nFinal Answer\nPlentiful",
        difficulty: "medium",
        topic: "synonyms",
        metadata: {
          generationStrategy: "DATASET",
          datasetItem: input.datasetItem,
        },
      };

      expect(() =>
        responseValidator.validate(
          question,
          "medium",
          "synonyms",
          input.template,
        ),
      ).not.toThrow();
    });

    it("should throw validation error if question contains raw template curly braces", () => {
      const template = {
        id: "tpl_vocab",
        name: "Vocabulary Synonym",
        conceptKey: "synonyms",
        difficultyLevel: "MEDIUM",
        questionType: "mcq",
        structure: {},
        variableSchema: {},
        constraints: {},
        generationStrategy: "DATASET",
      };

      const question: GeneratedQuestionDto = {
        question: "Select the synonym of the word {{word}}", // Placeholder leak
        options: ["Plentiful", "Scarce", "Few", "Tiny"],
        correctAnswer: "Plentiful",
        answer: "Plentiful",
        explanation:
          "Concept\n\nFormula / Reasoning\n\nStep-by-Step Solution\n\nFinal Answer\nPlentiful",
        difficulty: "medium",
        topic: "synonyms",
        metadata: {
          generationStrategy: "DATASET",
        },
      };

      expect(() =>
        responseValidator.validate(question, "medium", "synonyms", template),
      ).toThrow(
        "Question text contains unresolved template placeholder tokens",
      );
    });
  });

  describe("HYBRID Strategy", () => {
    it("should build prompt and validate family tree logical questions", () => {
      const input: PromptBuilderInput = {
        template: {
          id: "tpl_logic",
          name: "Family Tree Puzzle",
          conceptKey: "blood_relations",
          difficultyLevel: "HARD",
          questionType: "mcq",
          structure: {},
          variableSchema: {},
          constraints: {},
          generationStrategy: "HYBRID",
        },
        variableValues: {},
        logicalGraph: {
          entities: ["Rohan", "Amit", "Neha"],
          relations: [
            { source: "Rohan", target: "Amit", type: "brother" },
            { source: "Amit", target: "Neha", type: "father" },
          ],
        },
      };

      const prompt = promptBuilder.buildPrompt(input);
      expect(prompt).toContain("Generation Strategy: HYBRID");
      expect(prompt).toContain("Rohan is the brother of Amit");

      const question: GeneratedQuestionDto = {
        question:
          "Rohan is Amit's brother. Amit is Neha's father. How is Rohan related to Neha? (long prompt)",
        options: ["Uncle", "Brother", "Cousin", "Son"],
        correctAnswer: "Uncle",
        answer: "Uncle",
        explanation:
          "Concept\nBlood relations\n\nFormula / Reasoning\nUncle relation\n\nStep-by-Step Solution\nRohan is brother of father Amit, so uncle.\n\nFinal Answer\nUncle",
        difficulty: "hard",
        topic: "blood_relations",
        metadata: {
          generationStrategy: "HYBRID",
          logicalGraph: input.logicalGraph,
        },
      };

      expect(() =>
        responseValidator.validate(
          question,
          "hard",
          "blood_relations",
          input.template,
        ),
      ).not.toThrow();
    });

    it("should fail validation if generated question fails to reference graph entities", () => {
      const template = {
        id: "tpl_logic",
        name: "Family Tree Puzzle",
        conceptKey: "blood_relations",
        difficultyLevel: "HARD",
        questionType: "mcq",
        structure: {},
        variableSchema: {},
        constraints: {},
        generationStrategy: "HYBRID",
      };

      const question: GeneratedQuestionDto = {
        question:
          "John is Alice's brother. Alice is Bob's father. (Hallucinated names)",
        options: ["Uncle", "Brother", "Cousin", "Son"],
        correctAnswer: "Uncle",
        answer: "Uncle",
        explanation:
          "Concept\nBlood relations\n\nFormula / Reasoning\nUncle relation\n\nStep-by-Step Solution\nUncle.\n\nFinal Answer\nUncle",
        difficulty: "hard",
        topic: "blood_relations",
        metadata: {
          generationStrategy: "HYBRID",
          logicalGraph: {
            entities: ["Rohan", "Amit", "Neha"],
            relations: [],
          },
        },
      };

      expect(() =>
        responseValidator.validate(
          question,
          "hard",
          "blood_relations",
          template,
        ),
      ).toThrow("Logical reasoning validation failed");
    });
  });
});
