export enum DomainEvent {
    QUESTION_GENERATED = 'QUESTION_GENERATED',
  
    TEST_STARTED = 'TEST_STARTED',
  
    TEST_SUBMITTED = 'TEST_SUBMITTED',
  
    EVALUATION_COMPLETED = 'EVALUATION_COMPLETED',
  }