import React from 'react';
import { TemplateSection } from './TemplateSection';
import { PreviewBuilder } from './PreviewBuilder';
import { PreviewResultPanel } from './PreviewResultPanel';

export function PreviewSection() {
  return (
    <TemplateSection
      title='Template Preview'
      description='Provide variable values to simulate and preview the generated question, solution, and explanation.'
    >
      <div className='grid grid-cols-1 lg:grid-cols-2 gap-8'>
        <div className='space-y-4'>
          <div className='bg-gray-50 dark:bg-gray-900 border rounded-md p-4 flex flex-col justify-center text-sm text-gray-600 dark:text-gray-400'>
            <p>
              <strong>Instructions:</strong> Provide a valid JSON payload simulating the variables
              generated by the Variable Builder to see how the template renders.
            </p>
          </div>
          <PreviewBuilder />
        </div>

        <div className='space-y-4'>
          <PreviewResultPanel />
        </div>
      </div>
    </TemplateSection>
  );
}
