'use client';

import React from 'react';
import { TemplateSection } from '../TemplateSection';
import { VariableBuilderSection } from '../VariableBuilderSection';
import { ConstraintBuilderSection } from '../ConstraintBuilderSection';
import { OptionStrategySection } from '../OptionStrategySection';
import { QuestionDefinitionSection } from '../QuestionDefinitionSection';
import { SolutionLogicSection } from '../SolutionLogicSection';
import type { StrategyPanelProps } from '../../registry/strategy-panel.registry';

/**
 * VariableStrategyPanel
 *
 * Renders all variable-strategy specific sections by composing existing
 * components — no duplication of existing UI.
 */
export function VariableStrategyPanel({ templateId: _ }: StrategyPanelProps) {
  return (
    <div className="space-y-6">
      <TemplateSection
        title="Variable Strategy Configuration"
        description="Configure how mathematical variables, formulas, and constraints generate unique question instances."
      >
        <div className="p-3 bg-indigo-50 dark:bg-indigo-950/30 border border-indigo-200 dark:border-indigo-800 rounded-md">
          <p className="text-sm text-indigo-800 dark:text-indigo-300">
            <strong>Variable Strategy:</strong> Each question instance is generated by resolving variable
            values, evaluating formulas, and hydrating the question template. Every generated question
            is numerically unique.
          </p>
        </div>
      </TemplateSection>

      {/* Question Template — where variables are embedded as {{variableName}} */}
      <QuestionDefinitionSection />

      {/* Variable Builder — define variables, types, and generation rules */}
      <VariableBuilderSection />

      {/* Constraint Builder — define rules variables must satisfy */}
      <ConstraintBuilderSection />

      {/* Option Strategy — how distractors are generated */}
      <OptionStrategySection />

      {/* Solution & Explanation — template for the answer */}
      <SolutionLogicSection />
    </div>
  );
}
